### ISSUE TITLE
UrlLinker shouldn't be a final class

### ISSUE THREAD

**Issue by gabrielkoerich** [youthweb/urllinker#3]
Hi there!

I need to extend your class, but I can't because it's final. You should never make a package using a final class.

Please, make it extendable. 

Thanks =)

**Comment by Art4** [comment]
Hi and thank you for this issue.

The classes are final by design, see http://ocramius.github.io/blog/when-to-declare-classes-final/

If you want to change something you can build a decorator ahead of the interface like this:

```
<?php

use Youthweb\UrlLinker\UrlLinker;
use Youthweb\UrlLinker\UrlLinkerInterface;

class MyUrlLinker implements UrlLinkerInterface
{
	$urlLinker;
	/**
	 * @param string $text
	 * @return string
	 */
	public function __construct()
	{
		$this->urlLinker = new UrlLinker();
	}

	/**
	 * @param string $text
	 * @return string
	 */
	public function linkUrlsAndEscapeHtml($text)
	{
		return $this->urlLinker->linkUrlsAndEscapeHtml($text);
	}

	/**
	 * @param string $html
	 * @return string
	 */
	public function linkUrlsInTrustedHtml($html)
	{
		return $this->urlLinker->linkUrlsInTrustedHtml($html);
	}
}
```

The problem is, that the config getter and setter aren't yet in the interface. I will fix this immediately.

**Comment by Art4** [comment]
Can you provide a use case what you wanted to change with the extension? Maybe we can make UrlLinker more configurable for your use case.

**Comment by gabrielkoerich** [comment]
I know this post by ocramius, and I always try to create my classes final too.

I just don't think it should be done in packages. If a user wants to extend, let them do it.

But that's ok, I created a decorator as you advised. Thanks.

**Comment by Art4** [comment]
> I just don't think it should be done in packages. If a user wants to extend, let them do it.

Interesting. I would say especially packages are the target for final classes. This way a complete intern refactoring would never break someones implementation. If we let a user extend our classes, a refactoring wouldn't easy. Instead in proprietary/intern projects I would use fewer final classes because BC isn't so important there.

**Comment by gabrielkoerich** [comment]
Yeah but that's why we have tags, no? If you make BC break, you will probably create another version, even if your class is final. Interesting to see different points though.

**Comment by Art4** [comment]
This project follows [semver](http://semver.org/) and a BC break would lead to a major version increment. But we try to avoid that because BC breaks means always work for the user. Without the final classes we would have to pay attention with every refactoring not to break something, or we would end with a new major version after most refactoring.

The public API through the interfaces is our promise to the user that they can always update minor versions of our libraries without to care for BC breaks.
